id: P009335
initial_creation_type: ocr
source_metadata:
  id: bdr:W4CZ65545
  title: གསུང་འབུམ།  བློ་བཟང་བསྟན་པའི་ཉི་མ།
  author: ''
  volumes:
    9f660b27be24451f8aca710a7a6a2244:
      image_group_id: I4CZ65575
      title: ''
      volume_number: 1
      total_pages: 702
