id: P009335
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-19 19:34:00.722658
source_metadata:
  id: bdr:W4CZ65545
  title: གསུང་འབུམ།  བློ་བཟང་བསྟན་པའི་ཉི་མ།
  author: ''
  volumes:
    9f660b27be24451f8aca710a7a6a2244:
      image_group_id: I4CZ65575
      title: ''
      volume_number: 1
      total_pages: 702
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
