id: I8BED3DC7
legacy_id: P009335
ocr_import_info:
  bdrc_scan_id: W4CZ65545
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T21:02:02'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T20:54:56.552969+00:00'
last_modified: 2022-09-04 04:55:14.802385
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W4CZ65545
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW4CZ65545
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། བློ་བཟང་བསྟན་པའི་ཉི་མ།
  author: དཔོན་བླ ༠༢་བློ་བཟང་བསྟན་པའི་ཉི་མ།
statistics:
  ocr_word_mean_confidence_index: 0.6026574270561541
  ocr_word_median_confidence_index: 0.6100000143051147
quality: null
bases:
  I4CZ65575:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CZ65575
      total_pages: 702
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4CZ65575.txt
    statistics:
      ocr_word_median_confidence_index: 0.6100000143051147
      ocr_word_mean_confidence_index: 0.6026574270561541
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
